# add_user.yml
- hosts: all
  become: false
  tasks:
    - name: Создать нового пользователя
      user:
        name: admin1
        shell: /bin/bash
        create_home: yes
        groups: sudo
        state: present

    - name: Настроить авторизацию по SSH-ключу для нового пользователя
      authorized_key:
        user: admin1
        state: present
        key: "{{ lookup('file', '~/.ssh/igors_servers4096.pub') }}"  # путь к публичному ключу

    - name: Отключить доступ по паролю для всех пользователей
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
        create: yes

    - name: Install sudo package
      apt:
        name: sudo
        state: present

    - name: Allow sudo without password for the user
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^admin1 ALL=\(ALL\) NOPASSWD: ALL'
        line: 'admin1 ALL=(ALL) NOPASSWD: ALL'

    # Optionally, ensure that the user exists if not already created
    - name: Ensure admin1 user exists
      user:
        name: admin1
        state: present
        shell: /bin/bash
        groups: sudo
