- name: ELK Stack Setup
  hosts: logging
  become: true
  tasks:
    - name: Install Java
      apt:
        name: openjdk-11-jre
        state: present

    - name: Download and add the Elastic GPG key
      shell: |
        wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main" | tee /etc/apt/sources.list.d/elastic-8.x.list 

    - name: Install Elasticsearch
      apt_repository:
        repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
        state: present

    - name: Install Elasticsearch package
      apt:
        name: elasticsearch
        state: present

    - name: Start Elasticsearch
      command: "/usr/share/elasticsearch/bin/elasticsearch -d"
      args:
        chdir: /usr/share/elasticsearch  # Путь, откуда запускать команду
      become: false
      ignore_errors: yes  # Игнорируем ошибки, если процесс уже запущен


    - name: Start Elasticsearch
      service:
        name: elasticsearch
        state: started
        enabled: yes

    - name: Install Kibana
      apt:
        name: kibana
        state: present

    - name: Start Kibana
      service:
        name: kibana
        state: started
        enabled: yes

    - name: Install Logstash
      apt:
        name: logstash
        state: present

    - name: Create Logstash configuration file
      copy:
        dest: /etc/logstash/conf.d/nginx.conf
        content: |
          input {
            beats {
              port => 5044
            }
          }

          filter {
            grok {
              match => { "message" => "%{COMBINEDAPACHELOG}" }
            }
          }

          output {
            elasticsearch {
              hosts => ["localhost:9200"]
              index => "nginx-%{+YYYY.MM.dd}"
            }
          }

    - name: Start Logstash
      service:
        name: logstash
        state: started
        enabled: yes

