- name: LEMP Stack Setup
  hosts: web
  become: true
  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present

    - name: Install MySQL
      apt:
        name: mysql-server
        state: present

    - name: Install PHP and required extensions
      apt:
        name:
          - php-fpm
          - php-mysql
          - php-cli
        state: present

    - name: Configure NGINX to use PHP
      template:
        src: nginx.conf.j2  # Шаблон конфигурации NGINX
        dest: /etc/nginx/sites-available/default

    - name: Restart NGINX
      service:
        name: nginx
        state: restarted

