- name: Security Setup
  hosts: all
  become: true
  tasks:
    - name: Update and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install iptables firewall
      apt:
        name: iptables
        state: present

    - name: Install UFW firewall
      apt:
        name: ufw
        state: present

    - name: Allow all access to tcp port 80,5601,9200 #tried nft, iptables and others, but it need "root", but i use sudoer it seems like problem with docker on mac, using ufw inside container is working but with mistake.
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 80
      ignore_errors: yes

    - name: Deny all other traffic
      ufw:
        state: enabled
        policy: deny
      ignore_errors: yes
