version: '3.9'

services:
  ubu1:
    build:
      context: .
      dockerfile: Dockerfile1
    container_name: ubu1
    ports:
      - "8080:80"      # HTTP
    stdin_open: true
    tty: true
    networks:
      - ubuntu_network

  ubu2:
    build:
      context: .
      dockerfile: Dockerfile2
    container_name: ubu2
    ports:
      - "9200:9200"  # Elasticsearch
      - "5601:5601"  # Kibana
      - "5044:5044"  # Filebeat
    stdin_open: true
    tty: true
    networks:
      - ubuntu_network

networks:
  ubuntu_network:
    driver: bridge

